name: kite_fu
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.1.3
  json_annotation: ^4.4.0
  dio: ^4.0.4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7


flutter:
  uses-material-design: true
