name: "kite_fu"
description: "上应小风筝为您送来春节祝福~"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.1.3
  json_annotation: ^4.4.0
  dio: ^4.0.4
  intl: ^0.17.0
  shared_preferences: ^2.0.12
  url_launcher: ^6.0.17
  flash: ^2.0.3+1
  webviewx: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7


flutter:
  uses-material-design: true

  assets:
    - assets/scan/index.html